### PR TITLE
Add a revisions link and revision screen integration

### PR DESCRIPTION
**Pull request by adamsilverstein**
For https://github.com/10up/ads-txt/issues/1

### CODE REVIEW

**Comment by adamsilverstein** [comment]
> I got redirected back to the revisions screen after choosing to restore a revision; my expectation was that I would be taken back to the editor.

Hmmm, this was working at some point :) I'll get it working again!

> Placement/look of the revisions link needs some consideration. 

Any ideas where it would go/what to show exactly?

Hiding the title with css might be fine for now, if we can figure out how to only do that when you are viewing ads.txt

**Comment by adamsilverstein** [comment]
@helen:

* hid the title field with CSS. it works, although it is a bit ugly and fragile.

Screencast of this in action: https://cl.ly/bb1244cdda3f

Issus:

* The lack of an initial revision - we may want to create one manually when the Ads.txt file is saved for the first time
* Revisions count does not increment after updating the file, requires a refresh to update.
* Still need to decide about the best placement for the revisions link.

**Comment by jeffpaul** [comment]
@adamsilverstein mind checking out the merge conflict to resolve ahead of a 1.2 release?

**Comment by adamsilverstein** [comment]
* Resolved merge conflicts
* verified functions as expected. tested viewing, restoring revisions, going back to editor.

**Comment by helen** [comment]
Finally testing this:

1. I think the placement is actually fine. We could maybe tinker with the styling to make it look like the footer did on the classic editor, but I'm not too worried about it for now.
2. It confused me that it didn't save an initial revision so yes we should probably add that :)
3. It would be nice to show the updated count after save. I wonder if maybe we should just go ahead and do a full-page refresh upon successful save. That would also help differentiate it somewhat from the AJAX error checking.
4. And finally, a bug: restoring a revision needs to clear the previous error meta so it doesn't show up with error messages potentially unrelated to the restored content.

**Comment by adamsilverstein** [comment]
@helen thanks for the feedback. yea, updating the count be nice and a refresh makes sense and also fixes the issue of the revisions link not showing up when it should if you stay on the page and save several times (its hidden initially currently).

I'll add that as well as an initial save.

**Comment by helen** [comment]
There are still some PHPCS errors and it seems to additionally be barfing on some of the multiline (s)printf() calls + translator comments, but I'm going to ignore that for the moment so I think this is ready now.

I added the following:
* Deleting the `adstxt_errors` meta after restoring the revision.
* Showing a `Revisions restored` admin notice after restoring the revision.

**Pull request merged**
