### PR TITLE
Fix compatibility with Composer v2

### LINKED ISSUE #76: Plugin is incompatible with Composer v2
**Describe the bug**

When I try to use this plugin with Composer version 2.1.3, I get the following errors:
```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.5.0 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
```
And the solution is very simple since any version of the plugin prior to 0.7.0 only allowed installation on PHP 5.x and 7.x.
To fix the issue easily by running the command below:
`composer require --dev dealerdirect/phpcodesniffer-composer-installer:"^0.7.1"`

**Steps to Reproduce**

When I try to install dev dependencies by running the `composer i` command I get errors.

**Expected behavior**

Not getting errors while Install dependencies.
**Screenshots**

**Environment information**
 - Device: Laptop
 - OS: Fedora 35
 - Browser and version: Chrome (Not related)

**WordPress information**

<details><summary>Site Health info:</summary>

</details>

**Additional context**

I will provide a PR.

### PR DESCRIPTION
**Pull request by evokelektrique**
### Description of the Change

I mentioned the problem here #76 and the problem is very clear, we just need to update the related dependency to its latest version.

### Benefits

Composer version 1 is deprecated and we should move on to the newer version.

### Checklist:

- [X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my change.
- [X] All new and existing tests passed.

### Applicable Issues

#76 
### Changelog Entry

* Update `dealerdirect/phpcodesniffer-composer-installer` from **0.5.x** to **0.7.1**

### CODE REVIEW

**Review by peterwilsoncc — CHANGES_REQUESTED** [review]
According to the [readme](https://github.com/Dealerdirect/phpcodesniffer-composer-installer), this command needs to be run and the updated composer file committed:

```
composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
```

The tasks are currently stalled so I'll look at that now.

**Comment by peterwilsoncc** [comment]
Note: I've edited my review as I was hit with premature send syndrome.

**Comment by jeffpaul** [comment]
@evokelektrique are you able to make the update as noted above?

**Comment by evokelektrique** [comment]
@jeffpaul Oh I wasn't in GitHub for a while, Sure tomorrow I will take a look at it and see what is left.

**Comment by evokelektrique** [comment]
As @peterwilsoncc mentioned, I ran the command included in the readme and commit the changes.

**Review by peterwilsoncc — APPROVED** [review]
Thank @evokelektrique, these changes look good to me. The composer config changes allow the actions to run successfully.

_The action failures for this PR can be ignored, as they are triggered by a linting error introduced elsewhere._

**Pull request merged**
