### PR TITLE
Add Peter Wilson to contributor list.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Description of the Change

Adding me to the list of contributors in the WordPress.org readme file. This will ensure I'm listed as associated with the plugin when responding in the support forums.

I'm targeting this to trunk so the readme is updated without the need to release a new version.

Closes #

### Verification Process

I reviewed the [support forum user documentation](https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/#contributor) to ensure this was the best way to identify me as a contributor without needing commit.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

N/A

### Credits

N/A

### CODE REVIEW

**Comment by dkotter** [comment]
Tagging in @jeffpaul here to get his thoughts but I believe right now, we've been adding users to the Support Rep role through the settings on the plugin page on WordPress.org. Then when responding to support requests, their account will be marked as Plugin Support.

Would something like that achieve what you need here? I'm not opposed to adding new Contributors for those that are maintaining plugins but don't think we've been doing that up to this point (though doesn't mean we shouldn't start).

**Comment by peterwilsoncc** [comment]
> Would something like that achieve what you need here?

Yes, that would work.

**Comment by jeffpaul** [comment]
I had not thought about adding our stated maintainers as a contributor to appear on dotorg, though would be fine with that as we're already stating about the same thing in our CREDITS.md file.

**Review by dkotter — APPROVED** [review]

**Comment by dkotter** [comment]
> I had not thought about adding our stated maintainers as a contributor to appear on dotorg, though would be fine with that as we're already stating about the same thing in our CREDITS.md file.

I'm fine with that. Is there any plan to remove those that are no longer at 10up (seeing Helen and Adam here but there will surely be other instances of this in the future).

**Comment by peterwilsoncc** [comment]
> I'm fine with that. Is there any plan to remove those that are no longer at 10up (seeing Helen and Adam here but there will surely be other instances of this in the future).

I've created #99 for a follow up discussion and asked Helen and Adam for their thoughts.

**Comment by jeffpaul** [comment]
For folks who've historically had a large part in a project's development, I'm inclined to keep those folks listed.  Should they asked to be removed, for whatever reason, I'd be fine removing them then.  Otherwise I'd like to retain the recognition for their efforts.

**Pull request merged**
